version: '3'

services:
  backend:
    image: quay.io/hackthe6ix/hackthe6ix-backend:latest
    restart: always
    ports:
      - "6971:6971"
    env_file:
      - .env
    volumes:
      - ./data/backend-files/config:/usr/ht6/server/config
      - ./data/backend-files/logs:/usr/ht6/server/logs
  mongo:
    image: mongo:6-xenial
    restart: always
    volumes:
      - ./data/mongo-data:/data/db
networks:
  default:
    external:
      name: ht6_backend
