version: '3'

services:
  backend:
    image: hackthe6ix/backend:latest
    restart: always
    ports:
      - "6971:6971"
    env_file:
      - .env
    volumes:
      - ./data/backend-files/config:/usr/ht6/server/config
