apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hackthe6ix-backend.fullname" . }}
  labels:
    {{- include "hackthe6ix-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hackthe6ix-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.hackthe6ixBackend.secrets.vault.enabled -}}
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/tls-skip-verify: 'true'
        vault.hashicorp.com/role: '{{ .Values.hackthe6ixBackend.secrets.vault.role }}'
        vault.hashicorp.com/agent-inject-secret-env-source: {{ .Values.hackthe6ixBackend.secrets.vault.secretPath }}
        vault.hashicorp.com/agent-inject-file-env-source: backendEnv.sh
        vault.hashicorp.com/agent-inject-template-env-source: |
          {{ "{{" }}- with secret "{{ .Values.hackthe6ixBackend.secrets.vault.secretPath }}" -}}
          {{ "{{" }} range $k, $v := .Data.data }}
          export {{ "{{" }} $k }}={{ "{{" }} $v }}
          {{ "{{" }} end }}
          {{ "{{" }}- end }}
        {{- end }}
      labels:
        {{- include "hackthe6ix-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hackthe6ix-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
          {{- if not .Values.hackthe6ixBackend.secrets.vault.enabled }}
          envFrom:
            - secretRef:
                name: {{ include "hackthe6ix-backend.fullname" . }}-secrets
          {{- end }}
          env:
            - name: PORT
              value: "{{ .Values.service.port }}"
            - name: NODE_ENV
              value: "{{ .Values.hackthe6ixBackend.nodeEnv }}"
            - name: IDP_GROUP_PREFIX
              value: "{{ .Values.hackthe6ixBackend.auth.idpGroupPrefix }}"
            - name: AUTH_SETTINGS_CACHE_EVICT
              value: "{{ .Values.hackthe6ixBackend.auth.settingsCacheEviction }}"
            - name: LOG_LEVEL
              value: "{{ .Values.hackthe6ixBackend.logging.level }}"
            # Tracing configuration
            - name: ENABLE_TRACING
              value: "{{ .Values.hackthe6ixBackend.tracing.enabled }}"
            {{- if .Values.hackthe6ixBackend.tracing.enabled }}
            - name: GCP_TRACING_PROJECTID
              value: "{{ .Values.hackthe6ixBackend.tracing.projectId }}"
            - name: GCP_TRACING_KEYFILEPATH
              value: "/secrets/tracing/tracing-export-key.json"
            {{- end }}
            {{- if .Values.hackthe6ixBackend.mailer.enabled }}
            - name: MAILTRAIN_PUBLIC_ROOT_PATH
              value: "{{ .Values.hackthe6ixBackend.mailer.publicRoot }}"
            {{- end }}
            {{- if .Values.hackthe6ixBackend.secrets.vault.enabled }}
            - name: HT6_ENV_SOURCE
              value: /vault/secrets/backendEnv.sh
            {{- end }}
          volumeMounts:
            - name: initialization
              readOnly: true
              mountPath: /usr/ht6/server/config
            {{- if .Values.hackthe6ixBackend.tracing.enabled }}
            - name: tracing-export-key
              readOnly: true
              mountPath: /secrets/tracing
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- if .Values.hackthe6ixBackend.tracing.enabled }}
        - name: tracing-export-key
          secret:
            secretName: {{ .Values.hackthe6ixBackend.tracing.keyfile.secretName }}
            items:
              - key: {{ .Values.hackthe6ixBackend.tracing.keyfile.secretKey }}
                path: tracing-export-key.json
        {{- end }}
        - name: initialization
          secret:
            secretName: {{ .Values.hackthe6ixBackend.initialization.secretName }}
            items:
              - key: {{ .Values.hackthe6ixBackend.initialization.settings.secretKey }}
                path: settings.json
              - key: {{ .Values.hackthe6ixBackend.initialization.mailer.secretKey }}
                path: mailer.json

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}