{{- if .Values.ingressRoute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "hackthe6ix-backend.fullname" . }}
  namespace: webgtwy
spec:
  entryPoints:
    {{- range $entryPoint := .Values.ingressRoute.entryPoints }}
    - {{ $entryPoint }}
    {{- end }}
  routes:
    - match: Host(`{{ .Values.ingressRoute.host }}`)
      kind: Rule
      services:
        - name: {{ include "hackthe6ix-backend.fullname" . }}  # Requests will be forwarded to this service
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.service.port }}
  {{- with .Values.ingressRoute.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
