apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hackthe6ix-backend.fullname" . }}-secrets
data:
  DATABASE: {{ .Values.hackthe6ixBackend.mongoUrl | b64enc }}
  MAILTRAIN_API_KEY: {{ .Values.hackthe6ixBackend.mailer.apiKey | b64enc }}
  JWT_SECRET: {{ .Values.hackthe6ixBackend.auth.jwtSecret | b64enc }}
