{{- if not .Values.hackthe6ixBackend.secrets.vault.enabled -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hackthe6ix-backend.fullname" . }}-secrets
data:
  DATABASE: {{ .Values.hackthe6ixBackend.secrets.local.mongoUrl | b64enc }}
  MAILTRAIN_API_KEY: {{ .Values.hackthe6ixBackend.secrets.local.mailerApiKey | b64enc }}
  JWT_SECRET: {{ .Values.hackthe6ixBackend.secrets.local.jwtSecret | b64enc }}
  {{- end }}