image:
  pullPolicy: Always
  tag: develop

ingressRoute:
  tls:
    secretName: ht6-cforigin

hackthe6ixBackend:
  nodeEnv: development
  secrets:
    vault:
      enabled: true
      role: hackthe6ix-backend-staging
      secretPath: deploy/staging/backend
  tracing:
    enabled: false
  mailer:
    enabled: true
    publicRoot:
  initialization:
    secretName: ht6-backend-2023-staging-init
    settings:
      secretKey: settings.json
    mailer:
      secretKey: mailer.json