image:
  pullPolicy: Always
  tag: latest

ingressRoute:
  tls:
    secretName: ht6-cforigin

hackthe6ixBackend:
  nodeEnv: production
  secrets:
    vault:
      enabled: true
  tracing:
    enabled: true
    projectId: hack-the-6ix-production
  mailer:
    enabled: true
  initialization:
    secretName: ht6-backend-2023-init
    settings:
      secretKey: settings.json
    mailer:
      secretKey: mailer.json