name: Deploy to Kubernetes cluster
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environment_host:
        required: true
        type: string
      values_file:
        required: true
        type: string
      release_name:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: "ht6-backend"
    secrets:
      CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID:
        required: true
      CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET:
        required: true
      KUBECONFIG_B64:
        required: true
      MAILER_ROOT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.environment_host }}
    steps:
      - uses: actions/checkout@v3
      - name: Establish cluster connection using cloudflared
        uses: hack-the-6ix/cloudflared-tcp-action@main
        with:
          cloudflare_tunnel_service_token_id: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          cloudflare_tunnel_service_token_secret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}
          cloudflare_tunnel_hostname: "k8sapi-moose.hackthe6ix.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.0'
      - name: Apply Kubeconfig
        run: |
          mkdir -p ~/.kube/
          echo $KUBECONFIG_B64 | base64 -d > ~/.kube/config
        shell: bash
        env:
          KUBECONFIG_B64: ${{secrets.KUBECONFIG_B64}}
      - name: Deploy Helm chart
        run: |
          helm upgrade --install "$RELEASE_NAME" ./chart -f ./deploy/values.${VALUES_FILE}.yaml -n "$NAMESPACE" \
            --set hackthe6ixBackend.revision="$APP_REVISION" \
            --set ingressRoute.host="$DEPLOY_HOSTNAME" \
            --set hackthe6ixBackend.mailer.publicRoot="$MAILER_ROOT"
        shell: bash
        env:
          RELEASE_NAME: ${{ inputs.release_name }}
          NAMESPACE: ${{ inputs.namespace }}
          VALUES_FILE: ${{ inputs.values_file }}
          APP_REVISION: ${{ github.sha }}
          DEPLOY_HOSTNAME: ${{ vars.DEPLOY_HOSTNAME }}
          MAILER_ROOT: ${{ secrets.MAILER_ROOT }}
      - name: Remove Kubeconfig
        if: always()
        run: |
          rm -rf ~/.kube/config
        shell: bash
      - name: Shutdown cluster connection
        if: always()
        uses: hack-the-6ix/cloudflared-tcp-action/shutdown@main